macroScript thuy_place_OBJ category: "cartoonthuythuy" buttonText: "Thuy Place Obj"
Icon:#("thuy_icon_00",1)
(
	fileIn "D:\\Dropbox\\anhungxadieu_3d\\3dsmax\\maxscripts\\thuy_workWithObjs.ms"
	createDialog thuy_place_OBJ
)
macroScript thuy_UVXform category: "cartoonthuythuy" buttonText: "thuy uv xfrom"
Icon:#("thuy_icon_00",1)
(
	fileIn "D:\\Dropbox\\anhungxadieu_3d\\3dsmax\\maxscripts\\thuy_workWithObjs.ms"
	createDialog thuy_UVXform
)